server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: RatingServiceDB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  application:
    name: RATING-SERVICE  